# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tokansonar-proxy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://tokansonar.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a9cf26f6148145c590069246ab67da2d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a27959f444f545a19f65bf4a06d855c6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: tokansonar.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a9cf26f6148145c590069246ab67da2d }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tokansonar-proxy'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e423a81a4a844b15a8a296c9c4ec5131 }}
        images: 'tokansonar.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a9cf26f6148145c590069246ab67da2d }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'